apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmanager-data-gatherer
  labels:
    project: meicm-bm
    name: bookmanager-data-gatherer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bookmanager-data-gatherer
  template:
    metadata:
      labels:
        project: meicm-bm
        name: bookmanager-data-gatherer
    spec:
      containers:
      - name: bookmanager-data-gatherer
        env:
        - name: GR_KEY
          value: 5rdbqi8sOiUoyOpofYvxLA
        - name: SERVICE_DB_HOSTNAME
          value: bookmanager-database
        - name: SERVICE_DB_NAME
          value: bookmanager
        - name: SERVICE_DB_PORT
          value: "27017"
        - name: SERVICE_PORT
          value: "10004"
        ports:
        - containerPort: 10004
        image: bookmanager_data_gatherer_service:1.0.1
        imagePullPolicy: Never
        resources: {}
      restartPolicy: Always
      
